apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: hoangvu753/test-repo:test-consumer
        ports:
        - containerPort: 3002
        env:
        - name: RABBITMQ_URL
          value: "amqp://user:password@rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
