apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: producer
spec:
  type: NodePort  # Change this line to expose service externally
  ports:
    - port: 3001    # Service port
      targetPort: 3001
      nodePort: 30001  # External port you can access via the node's IP
  selector:
    app: producer
